name: 'Fetch API Data'
description: 'This action will handle authenticated API requests, allowing you to save the data from the request into your workspace.'
author: 'James Ives <iam@jamesiv.es>'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'truck'
  color: 'purple'
inputs:
  ENDPOINT:
    description: 'The URL of the endpoint you would like to retrieve data from.'
    required: true

  CONFIGURATION: 
    description: 'Any applicable configuration settings that should be set such as authentication tokens. You can reference secrets using the secrets syntax, or you can reference data returned from the `TOKEN_ENDPOINT` request using the triple bracket syntax.'
    required: false

  TOKEN_ENDPOINT:
    description: 'If the `ENDPOINT` API requires you to make a request to get an access token prior to fetching data you can perform this task by specifying a token endpoint. Any data returned from the token end can be referenced in the `CONFIGURATION` variable using the triple bracket syntax.'
    required: false

  TOKEN_CONFIGURATION:
    description: 'Any applicable configuration settings that should be set such as authentication tokens. You can reference secrets using the secrets syntax.'
    required: false

  SAVE_LOCATION:
    description: 'By default the save location of the JSON file is `fetch-api-data-action/data.json`, if you would like to override the directory you can do so by specifying a new one with this variable.'
    required: false

  SAVE_NAME:
    description: 'You can override the name of the exported `.json` file by specifying a new one here. You should _not_ include the file extension in your name.'
    required: false

outputs:
  FETCH_API_DATA:
    description: 'The requested data from the API stored as a string.'