name: unit-tests
on:
  pull_request:
    branches:
      - dev
      - releases/v1
      - releases/v2
  push:
    branches:
      - dev
    tags-ignore:
      - '*.*'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install and Test
        run: |
          yarn install --frozen-lockfile
          yarn lint:check
          yarn lint:format:check
          yarn test

      - name: Uploade CodeCov Report
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
