name: Integration Tests 🧪
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
  push:
    tags-ignore:
      - '*.*'
    branches:
      - releases/v*
jobs:
  refresh-api-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5.0.1
        with:
          persist-credentials: false

      - name: Fetch UTF8 Data 📦
        id: validate
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://jsonplaceholder.typicode.com/todos/1
          save-location: fetch-api-data-custom
          save-name: todo
          retry: true

      - name: Access environment variable output
        run: |
          echo "${fetchApiData}"

      - name: Access step output
        run: |
          echo "Output: ${{ steps.validate.outputs.fetchApiData }}"

      - name: Build and Deploy Repo 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: fetch-api-data-custom
          target-folder: data
          ssh-key: ${{ secrets.DEPLOY_KEY }}
